//Loadout presets

/obj/item/modular_computer/laptop/preset/custom_loadout/cheap/install_default_hardware()
	..()
	hardware_installed += new/obj/item/weapon/computer_hardware/processor_unit/small(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/tesla_link(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/hard_drive/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/network_card/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/nano_printer(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/card_slot(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/battery_module/advanced(src)
	battery_module.charge_to_full()

/obj/item/modular_computer/laptop/preset/custom_loadout/advanced/install_default_hardware()
	..()
	hardware_installed += new/obj/item/weapon/computer_hardware/processor_unit(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/tesla_link(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/hard_drive/advanced(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/network_card/advanced(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/nano_printer(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/card_slot(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/battery_module/advanced(src)
	battery_module.charge_to_full()

/obj/item/modular_computer/laptop/preset/custom_loadout/standard/install_default_hardware()
	..()
	hardware_installed += new/obj/item/weapon/computer_hardware/processor_unit(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/tesla_link(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/hard_drive/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/network_card/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/nano_printer(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/card_slot(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/battery_module/advanced(src)
	battery_module.charge_to_full()

/obj/item/modular_computer/laptop/preset/custom_loadout/install_default_programs()
	..()
	var/mob/living/carbon/human/H = get_holder_of_type(src, /mob)
	if(!istype(H)) return
	install_default_programs_by_job(H)
	boot_device.store_file(new/datum/computer_file/program/wordprocessor())

//Map presets

/obj/item/modular_computer/laptop/preset/records/install_default_hardware()
	..()
	hardware_installed += new/obj/item/weapon/computer_hardware/processor_unit/small(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/tesla_link(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/hard_drive/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/network_card/(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/nano_printer(src)
	hardware_installed += new/obj/item/weapon/computer_hardware/battery_module/nano(src)
	battery_module.charge_to_full()
	hardware_installed += new /obj/item/weapon/computer_hardware/scanner/paper(src)

/obj/item/modular_computer/laptop/preset/records/install_default_programs()
	..()
	boot_device.store_file(new/datum/computer_file/program/records())
	boot_device.store_file(new/datum/computer_file/program/wordprocessor())